# Generated by Django 4.0.6 on 2022-07-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_problem_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
