# Generated by Django 4.0.6 on 2022-07-23 10:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_remove_problem_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='author',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9-_ ]{1,64}$')]),
        ),
    ]
