LANGUAGES = set(
    (
        "ada",
        "c",
        "c#",
        "c++",
        "d",
        "go",
        "haskell",
        "java",
        "javascript",
        "lua",
        "ocaml",
        "pascal",
        "perl",
        "php",
        "prolog",
        "python",
        "ruby",
        "rust",
        "scheme",
    )
)
