---
repos:
  - repo: https://github.com/python/black
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3.10
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.19.0
    hooks:
      - id: eslint
        entry: bash -c 'cd frontend && yarn lint --fix'
        files: "\\.(js|jsx|ts|tsx)$"
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17
    hooks:
      - id: shellcheck
