# Generated by Django 4.0.2 on 2022-06-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("status", models.CharField(max_length=150)),
            ],
            options={
                "managed": False,
            },
        ),
    ]
