files: evaluator/.*
exclude: "(evaluator/evaluator/settings/.*|evaluator/.*/migrations/.*)"
repos:
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: ["--count", "--ignore=E731,W503" ,"--show-source", "--statistics"]
