# Generated by Django 4.0.6 on 2022-07-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_class_student_prologinuser_is_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='name',
            field=models.CharField(default='Prologin class', max_length=64),
        ),
    ]
