# Generated by Django 4.0.6 on 2022-07-27 10:28

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
