# Generated by Django 4.0.6 on 2022-07-27 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0005_remove_class_id_alter_class_temp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='temp_id',
            new_name='id',
        ),
    ]
