# Generated by Django 4.0.2 on 2022-06-14 17:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django_resized.forms
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9-_]{4,64}$')])),
                ('author', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPG', keep_meta=False, quality=75, size=[400, 600], upload_to='./uploads/images/activies/{title}')),
                ('opening', models.DateTimeField(blank=True, null=True)),
                ('closing', models.DateTimeField(blank=True, null=True)),
                ('publication', models.DateTimeField()),
                ('managers', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('problems', models.ManyToManyField(to='problems.Problem')),
            ],
            options={
                'verbose_name_plural': 'activities',
            },
        ),
    ]
