# Generated by Django 4.0.2 on 2022-06-15 08:31

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=["middle", "center"],
                force_format="JPEG",
                keep_meta=False,
                quality=75,
                size=[400, 600],
                upload_to="./uploads/images/activies/{title}",
            ),
        ),
    ]
