# Generated by Django 4.0.2 on 2022-06-15 15:38

import activities.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_alter_activity_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=False, null=True, quality=75, size=[600, 400], upload_to=activities.models.upload_image),
        ),
    ]
