# Generated by Django 4.0.6 on 2022-07-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_remove_activity_publication_activity_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='published',
            field=models.BooleanField(),
        ),
    ]
