# Generated by Django 4.0.6 on 2022-07-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_class_temp_id_alter_class_students'),
        ('activities', '0011_alter_activity_author_alter_activity_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='authorized_classes',
            field=models.ManyToManyField(to='authentification.class'),
        ),
    ]
