# Generated by Django 4.0.2 on 2022-06-14 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("problems", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProblemSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("validated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="problems.problem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProblemSubmissionCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("c", "c"),
                            ("scheme", "scheme"),
                            ("ada", "ada"),
                            ("perl", "perl"),
                            ("c#", "c#"),
                            ("c++", "c++"),
                            ("python", "python"),
                            ("java", "java"),
                            ("go", "go"),
                            ("php", "php"),
                            ("pascal", "pascal"),
                            ("haskell", "haskell"),
                            ("ocaml", "ocaml"),
                            ("prolog", "prolog"),
                            ("d", "d"),
                            ("ruby", "ruby"),
                            ("javascript", "javascript"),
                            ("lua", "lua"),
                            ("rust", "rust"),
                        ],
                        max_length=32,
                    ),
                ),
                ("code", models.TextField()),
                (
                    "summary",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("date_submitted", models.DateTimeField(auto_now_add=True)),
                (
                    "date_corrected",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("result", models.JSONField(blank=True, null=True)),
                ("validated", models.BooleanField(default=False)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="submissions.problemsubmission",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="problemsubmission",
            name="validated_by",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="submissions.problemsubmissioncode",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="problemsubmission",
            unique_together={("problem", "user")},
        ),
    ]
