# Generated by Django 4.0.6 on 2022-07-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_alter_problemsubmissioncode_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemsubmissioncode',
            name='language',
            field=models.CharField(choices=[('php', 'php'), ('javascript', 'javascript'), ('python', 'python'), ('perl', 'perl'), ('lua', 'lua'), ('d', 'd'), ('c++', 'c++'), ('haskell', 'haskell'), ('ruby', 'ruby'), ('c#', 'c#'), ('ada', 'ada'), ('java', 'java'), ('scheme', 'scheme'), ('ocaml', 'ocaml'), ('prolog', 'prolog'), ('pascal', 'pascal'), ('go', 'go'), ('rust', 'rust'), ('c', 'c')], max_length=32),
        ),
    ]
