# Generated by Django 4.0.6 on 2022-07-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_alter_problemsubmissioncode_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemsubmissioncode',
            name='language',
            field=models.CharField(choices=[('rust', 'rust'), ('d', 'd'), ('java', 'java'), ('ocaml', 'ocaml'), ('c++', 'c++'), ('ruby', 'ruby'), ('perl', 'perl'), ('javascript', 'javascript'), ('c', 'c'), ('lua', 'lua'), ('ada', 'ada'), ('haskell', 'haskell'), ('python', 'python'), ('c#', 'c#'), ('php', 'php'), ('scheme', 'scheme'), ('go', 'go'), ('prolog', 'prolog'), ('pascal', 'pascal')], max_length=32),
        ),
    ]
