# Generated by Django 4.0.6 on 2022-07-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0009_alter_problemsubmissioncode_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemsubmissioncode',
            name='language',
            field=models.CharField(choices=[('perl', 'perl'), ('ocaml', 'ocaml'), ('c#', 'c#'), ('ruby', 'ruby'), ('c++', 'c++'), ('go', 'go'), ('c', 'c'), ('d', 'd'), ('lua', 'lua'), ('prolog', 'prolog'), ('php', 'php'), ('haskell', 'haskell'), ('java', 'java'), ('scheme', 'scheme'), ('python', 'python'), ('rust', 'rust'), ('ada', 'ada'), ('javascript', 'javascript'), ('pascal', 'pascal')], max_length=32),
        ),
    ]
