# Generated by Django 4.0.6 on 2022-07-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0010_alter_problemsubmissioncode_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemsubmissioncode',
            name='language',
            field=models.CharField(choices=[('pascal', 'pascal'), ('c#', 'c#'), ('c++', 'c++'), ('ocaml', 'ocaml'), ('javascript', 'javascript'), ('ada', 'ada'), ('python', 'python'), ('scheme', 'scheme'), ('rust', 'rust'), ('lua', 'lua'), ('perl', 'perl'), ('c', 'c'), ('d', 'd'), ('prolog', 'prolog'), ('php', 'php'), ('go', 'go'), ('java', 'java'), ('ruby', 'ruby'), ('haskell', 'haskell')], max_length=32),
        ),
    ]
