# Generated by Django 4.0.6 on 2022-07-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0011_alter_problemsubmissioncode_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemsubmissioncode',
            name='language',
            field=models.CharField(choices=[('ocaml', 'ocaml'), ('python', 'python'), ('d', 'd'), ('c++', 'c++'), ('ruby', 'ruby'), ('haskell', 'haskell'), ('lua', 'lua'), ('c#', 'c#'), ('ada', 'ada'), ('java', 'java'), ('pascal', 'pascal'), ('rust', 'rust'), ('php', 'php'), ('javascript', 'javascript'), ('c', 'c'), ('go', 'go'), ('scheme', 'scheme'), ('prolog', 'prolog'), ('perl', 'perl')], max_length=32),
        ),
    ]
