# Generated by Django 4.0.6 on 2022-07-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0012_alter_problemsubmissioncode_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemsubmissioncode',
            name='language',
            field=models.CharField(choices=[('d', 'd'), ('scheme', 'scheme'), ('php', 'php'), ('lua', 'lua'), ('javascript', 'javascript'), ('ocaml', 'ocaml'), ('perl', 'perl'), ('ruby', 'ruby'), ('haskell', 'haskell'), ('c++', 'c++'), ('prolog', 'prolog'), ('go', 'go'), ('c#', 'c#'), ('c', 'c'), ('rust', 'rust'), ('java', 'java'), ('python', 'python'), ('pascal', 'pascal'), ('ada', 'ada')], max_length=32),
        ),
    ]
