# Generated by Django 4.0.6 on 2022-07-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0013_alter_problemsubmissioncode_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemsubmissioncode',
            name='language',
            field=models.CharField(choices=[('rust', 'rust'), ('scheme', 'scheme'), ('javascript', 'javascript'), ('python', 'python'), ('ruby', 'ruby'), ('java', 'java'), ('c++', 'c++'), ('go', 'go'), ('prolog', 'prolog'), ('haskell', 'haskell'), ('c#', 'c#'), ('ada', 'ada'), ('c', 'c'), ('d', 'd'), ('pascal', 'pascal'), ('lua', 'lua'), ('ocaml', 'ocaml'), ('php', 'php'), ('perl', 'perl')], max_length=32),
        ),
    ]
