# Generated by Django 4.0.6 on 2022-07-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0014_alter_problemsubmissioncode_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemsubmissioncode',
            name='language',
            field=models.CharField(choices=[('ada', 'ada'), ('go', 'go'), ('lua', 'lua'), ('python', 'python'), ('c++', 'c++'), ('perl', 'perl'), ('prolog', 'prolog'), ('c', 'c'), ('pascal', 'pascal'), ('rust', 'rust'), ('d', 'd'), ('c#', 'c#'), ('ocaml', 'ocaml'), ('haskell', 'haskell'), ('php', 'php'), ('ruby', 'ruby'), ('scheme', 'scheme'), ('java', 'java'), ('javascript', 'javascript')], max_length=32),
        ),
    ]
