# Generated by Django 4.0.6 on 2022-07-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0015_alter_problemsubmissioncode_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemsubmissioncode',
            name='language',
            field=models.CharField(choices=[('d', 'd'), ('perl', 'perl'), ('javascript', 'javascript'), ('pascal', 'pascal'), ('prolog', 'prolog'), ('c#', 'c#'), ('haskell', 'haskell'), ('ruby', 'ruby'), ('c++', 'c++'), ('rust', 'rust'), ('ocaml', 'ocaml'), ('scheme', 'scheme'), ('php', 'php'), ('python', 'python'), ('go', 'go'), ('java', 'java'), ('c', 'c'), ('ada', 'ada'), ('lua', 'lua')], max_length=32),
        ),
    ]
