# Generated by Django 4.0.6 on 2022-07-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0017_alter_problemsubmissioncode_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemsubmissioncode',
            name='language',
            field=models.CharField(choices=[('lua', 'lua'), ('c#', 'c#'), ('go', 'go'), ('scheme', 'scheme'), ('ruby', 'ruby'), ('python', 'python'), ('java', 'java'), ('ocaml', 'ocaml'), ('d', 'd'), ('prolog', 'prolog'), ('rust', 'rust'), ('c', 'c'), ('haskell', 'haskell'), ('ada', 'ada'), ('perl', 'perl'), ('php', 'php'), ('c++', 'c++'), ('pascal', 'pascal'), ('javascript', 'javascript')], max_length=32),
        ),
    ]
