# Generated by Django 4.0.6 on 2022-07-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0018_alter_problemsubmissioncode_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemsubmissioncode',
            name='language',
            field=models.CharField(choices=[('php', 'php'), ('haskell', 'haskell'), ('javascript', 'javascript'), ('c++', 'c++'), ('java', 'java'), ('lua', 'lua'), ('pascal', 'pascal'), ('perl', 'perl'), ('ocaml', 'ocaml'), ('ruby', 'ruby'), ('prolog', 'prolog'), ('c#', 'c#'), ('go', 'go'), ('rust', 'rust'), ('scheme', 'scheme'), ('ada', 'ada'), ('d', 'd'), ('python', 'python'), ('c', 'c')], max_length=32),
        ),
    ]
