# Generated by Django 4.0.6 on 2022-07-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0019_alter_problemsubmissioncode_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemsubmissioncode',
            name='language',
            field=models.CharField(choices=[('ada', 'ada'), ('c++', 'c++'), ('pascal', 'pascal'), ('c#', 'c#'), ('ruby', 'ruby'), ('python', 'python'), ('haskell', 'haskell'), ('java', 'java'), ('rust', 'rust'), ('lua', 'lua'), ('d', 'd'), ('javascript', 'javascript'), ('c', 'c'), ('perl', 'perl'), ('ocaml', 'ocaml'), ('prolog', 'prolog'), ('php', 'php'), ('go', 'go'), ('scheme', 'scheme')], max_length=32),
        ),
    ]
