# Generated by Django 4.0.6 on 2022-07-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0020_alter_problemsubmissioncode_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemsubmissioncode',
            name='language',
            field=models.CharField(choices=[('scheme', 'scheme'), ('ada', 'ada'), ('prolog', 'prolog'), ('go', 'go'), ('ocaml', 'ocaml'), ('python', 'python'), ('perl', 'perl'), ('javascript', 'javascript'), ('php', 'php'), ('rust', 'rust'), ('c', 'c'), ('c++', 'c++'), ('c#', 'c#'), ('pascal', 'pascal'), ('haskell', 'haskell'), ('lua', 'lua'), ('java', 'java'), ('d', 'd'), ('ruby', 'ruby')], max_length=32),
        ),
    ]
