# Generated by Django 4.0.6 on 2022-07-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0021_alter_problemsubmissioncode_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemsubmissioncode',
            name='language',
            field=models.CharField(choices=[('c', 'c'), ('perl', 'perl'), ('haskell', 'haskell'), ('python', 'python'), ('c#', 'c#'), ('lua', 'lua'), ('javascript', 'javascript'), ('d', 'd'), ('pascal', 'pascal'), ('go', 'go'), ('ada', 'ada'), ('c++', 'c++'), ('prolog', 'prolog'), ('rust', 'rust'), ('ruby', 'ruby'), ('java', 'java'), ('php', 'php'), ('ocaml', 'ocaml'), ('scheme', 'scheme')], max_length=32),
        ),
    ]
