---
version: "3.8"

services:

  s3_dev:
    image: scality/s3server
    hostname: s3_dev
    restart: unless-stopped
    environment:
      MINIO_ACCESS_KEY_FILE: s3-access
      MINIO_SECRET_KEY_FILE: s3-secret
      S3DATAPATH: /data
      S3METADATAPATH: /metadata
      ENDPOINT: s3-dev
    secrets:
      - s3-access
      - s3-secret
    ports:
      - "$S3_PORT:8000"
    volumes:
      - s3_dev_data:/data
      - s3_dev_metadata:/metadata

  db_dev:
    image: postgres:13
    hostname: db_dev
    restart: unless-stopped
    shm_size: 256M
    environment:
      POSTGRES_USER: template_dev
      POSTGRES_DB: template_dev
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd
    secrets:
      - postgres-passwd
    volumes:
      - db_dev_data:/var/lib/postgresql/data

  db_pgadmin_dev:
    image: dpage/pgadmin4:6.11
    hostname: db_pgadmin_dev
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: info@prologin.org
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin-passwd
    ports:
      - "$PGADMIN_PORT:80"
    depends_on:
      - db_dev
      - backend_dev
    secrets:
      - pgadmin-passwd
    volumes:
      - ./config/servers.json:/pgadmin4/servers.json
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "echo 'db_dev:5432:*:template_dev:29EdkmCHLtUxyFlA76DrhrsNOJmNTgkl' > /tmp/pgpass && chmod 600 /tmp/pgpass && /entrypoint.sh"

  redis_dev:
    image: redis:7.0.3
    hostname: redis_dev
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - redis_dev_data:/data

  celery_dev:
    restart: unless-stopped
    build:
      context: ../backend
    command: celery -A evaluator worker -l info --concurrency=4
    env_file:
      - ./.env.dev
    depends_on:
      - redis_dev
      - backend_dev
    volumes:
      - type: bind
        source: ../backend
        target: /app/template/
    secrets:
      - django-secret-key
      - postgres-passwd
      - s3-access
      - s3-secret

  celery_flower_dev:
    image: mher/flower
    hostname: db_adminer_dev
    restart: unless-stopped
    environment:
      - CELERY_BROKER_URL=redis://redis_dev:6379/0
      - FLOWER_PORT=8888
    ports:
      - $FLOWER_PORT:8888
    depends_on:
      - celery_dev
      - redis_dev

  backend_dev:
    image: backend_dev
    build:
      context: ../backend
      args:
        DJANGO_UID: 1000
        DJANGO_GID: 1000
        BUILDKIT_INLINE_CACHE: 1
    restart: unless-stopped
    env_file:
      - ./.env.dev
    environment:
      - S3_CUSTOM_DOMAIN=localhost:$S3_PORT/evaluator
    depends_on:
      - db_dev
      - s3_dev
      - redis_dev
    links:
      - s3_dev:s3-dev
    volumes:
      - type: bind
        source: ../backend
        target: /app/template/
      - type: bind
        source: ./volumes/ipython
        target: /app/.ipython
      - type: bind
        source: ./config/cors.json
        target: /app/cors.json
    secrets:
      - django-secret-key
      - postgres-passwd
      - s3-access
      - s3-secret

  frontend_dev:
    image: frontend_dev
    build:
      context: ../frontend
      args:
        BUILDKIT_INLINE_CACHE: 1
    restart: unless-stopped
    environment:
      DEV: 1
    volumes:
      - type: bind
        source: ../frontend
        target: /app/template

  reverse_dev:
    image: nginx
    ports:
      - $REVERSE_PORT:80
    restart: unless-stopped
    depends_on:
      - frontend_dev
    volumes:
      - type: bind
        source: ./config/nginx.conf
        target: /etc/nginx/nginx.conf
volumes:
  db_dev_data: {}
  s3_dev_data: {}
  s3_dev_metadata: {}
  redis_dev_data: {}

secrets:
  django-secret-key:
    file: ./secrets/django-secret-key
  postgres-passwd:
    file: ./secrets/postgres-passwd
  s3-access:
    file: ./secrets/s3-access
  s3-secret:
    file: ./secrets/s3-secret
  pgadmin-passwd:
    file: ./secrets/pgadmin-passwd
