# Generated by Django 4.0.2 on 2022-03-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problemsubmissioncode",
            name="language",
            field=models.CharField(
                choices=[
                    ("go", "go"),
                    ("ruby", "ruby"),
                    ("php", "php"),
                    ("d", "d"),
                    ("ada", "ada"),
                    ("python", "python"),
                    ("scheme", "scheme"),
                    ("lua", "lua"),
                    ("prolog", "prolog"),
                    ("rust", "rust"),
                    ("java", "java"),
                    ("javascript", "javascript"),
                    ("c#", "c#"),
                    ("c++", "c++"),
                    ("haskell", "haskell"),
                    ("ocaml", "ocaml"),
                    ("pascal", "pascal"),
                    ("perl", "perl"),
                    ("c", "c"),
                ],
                max_length=32,
            ),
        ),
    ]
