# Generated by Django 4.0.2 on 2022-04-22 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_alter_problemsubmissioncode_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemsubmission',
            name='validated_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='submissions.problemsubmissioncode'),
        ),
        migrations.AlterField(
            model_name='problemsubmissioncode',
            name='language',
            field=models.CharField(choices=[('ocaml', 'ocaml'), ('prolog', 'prolog'), ('c', 'c'), ('rust', 'rust'), ('haskell', 'haskell'), ('python', 'python'), ('go', 'go'), ('perl', 'perl'), ('pascal', 'pascal'), ('d', 'd'), ('java', 'java'), ('scheme', 'scheme'), ('c#', 'c#'), ('php', 'php'), ('javascript', 'javascript'), ('ruby', 'ruby'), ('c++', 'c++'), ('ada', 'ada'), ('lua', 'lua')], max_length=32),
        ),
    ]
