# Generated by Django 4.0.2 on 2022-05-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prologinuser',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='prologinuser',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
    ]
