# Generated by Django 4.0.2 on 2022-05-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_alter_prologinuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='prologinuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='prologinuser',
            name='birthdate',
            field=models.DateField(),
        ),
    ]
