# Generated by Django 4.0.2 on 2022-05-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_alter_prologinuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prologinuser',
            name='accept_newsletter',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
