# Generated by Django 4.0.2 on 2022-05-06 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='author',
            field=models.CharField(default='WEJDENE', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='version',
            field=models.CharField(max_length=384, validators=[django.core.validators.RegexValidator('[a-f0-9]{7,}')]),
        ),
    ]
