# Generated by Django 4.0.2 on 2022-05-21 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_alter_problem_title'),
        ('activities', '0001_initial'),
    ]

    operations = [
            migrations.RemoveField(
                model_name='activity',
                name='slug',
                ),
            migrations.RemoveField(
                model_name='activity',
                name='problems',
                ),
            migrations.AddField(
                model_name='activity',
                name='problems',
                field=models.ManyToManyField(related_name='activity', to='problems.Problem'),
                ),
            migrations.AlterField(
                model_name='activity',
                name='title',
                field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9-_]{4,64}$')]),
                ),
            migrations.AlterField(
                model_name='activity',
                name='version',
                field=models.PositiveIntegerField(default=1),
                ),
            migrations.DeleteModel(
                name='ActivityProblem',
                ),
            ]
