# Generated by Django 4.0.2 on 2022-05-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_alter_problem_title'),
        ('activities', '0002_remove_activity_slug_alter_activity_problems_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='problems',
            field=models.ManyToManyField(to='problems.Problem'),
        ),
    ]
