# Generated by Django 4.0.2 on 2022-05-18 21:16

from django.db import migrations, models
import problems.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('subject', models.TextField()),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(0, 'trivial'), (1, 'easy'), (2, 'medium'), (3, 'hard'), (4, 'very_hard')])),
                ('allowed_languages', models.JSONField(validators=[problems.validators.allowed_languages_validator])),
                ('skeletons', models.JSONField(blank=True, validators=[problems.validators.language_string_mapping_validator])),
                ('correction_templates', models.JSONField(blank=True, validators=[problems.validators.language_string_mapping_validator])),
                ('tests', models.JSONField(validators=[problems.validators.tests_validator])),
            ],
        ),
    ]
